<a href="https://colab.research.google.com/github/kroberts32-dev/world_health_repo/blob/main/GB885_Assignment_5_Roberts_K.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#World Health Data

Kasandra Roberts

In [1]:
#import necessary libraries
import pandas as pd
import numpy as np

In [2]:
#read a csv file from a url to a pandas dataframe

url = 'https://raw.githubusercontent.com/katiegaertner/ML-Fundamentals/main/world-health-data-numbers.csv'
world_health_data = pd.read_csv(url)

#check  work
world_health_data.head()

,Country,Pop_Density,Abbreviation,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
0,Andorra,164.0,AD,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
1,United Arab Emirates,118.0,AE,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
2,Afghanistan,60.0,AF,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
3,Antigua and Barbuda,223.0,AG,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
4,Albania,105.0,AL,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

In [3]:
# create dataframe
world_health_df = pd.DataFrame(world_health_data)

world_health_df.head()

,Country,Pop_Density,Abbreviation,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
0,Andorra,164.0,AD,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
1,United Arab Emirates,118.0,AE,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
2,Afghanistan,60.0,AF,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
3,Antigua and Barbuda,223.0,AG,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
4,Albania,105.0,AL,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12

### Question 1: How man rows are in the DataFrame?

### Question 2: How many columns are in the DataFrame?

In [4]:
# use shape to find row count
world_health_data.shape

(194, 18)

## Update Notebook

View the first 5 rows of the DataFrame

Update the Abbreviations column to be the index

In [5]:
# Set abbreviations column as index

world_health_df = world_health_df.set_index('Abbreviation')

In [6]:
#Check work
world_health_df

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
AD,Andorra,164.0,468.0,7.20,469.0,NaN,1.27,3.154058e+09,2.7,NaN,NaN,6.63,Catalan,0.36,3.33,77142.0,NaN
AE,United Arab Emirates,118.0,83600.0,10.33,206324.0,114.52,1.41,4.211420e+11,6.5,77.8,3.0,NaN,Arabic,0.18,2.53,9770529.0,0.02
AF,Afghanistan,60.0,652230.0,32.49,8672.0,149.90,4.47,1.910135e+10,47.9,64.5,638.0,0.43,Pashto,0.78,0.28,38041754.0,0.11
AG,Antigua and Barbuda,223.0,443.0,15.33,557.0,113.81,1.99,1.727759e+09,5.0,76.9,42.0,3.04,English,0.24,2.76,97118.0,NaN
AL,Albania,105.0,28748.0,11.78,4536.0,119.05,1.62,1.527808e+10,7.8,78.5,15.0,1.12,Albanian,0.57,1.20,2854191.0,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EW,Eswatini,67.0,17364.0,NaN,NaN,NaN,NaN,3.791304e+09,NaN,NaN,NaN,NaN,English,0.11,NaN,1093238.0,NaN
VA,Vatican City,2003.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Italian,NaN,NaN,836.0,NaN
RI,Republic of Ireland,72.0,70273.0,12.50,37711.0,106.58,1.75,3.886990e+11,3.1,82.3,5.0,10.79,Irish,0.15,3.31,5007069.0,0.05
NB,Namibia,3.0,824292.0,28.64,4228.0,157.97,3.40,1.236653e+10,29.0,63.4,195.0,NaN,English,0.08,0.42,2494530.0,0.20
NM,North Macedonia,83.0,25713.0,NaN,NaN,NaN,NaN,1.022078e+10,NaN,NaN,NaN,NaN,Macedonian,0.36,NaN,1836713.0,NaN

In [7]:
#sort DataFrame by index
world_health_df = world_health_df.sort_index()

###Question 3: What nation has the index value "DZ"

In [8]:
world_health_df.loc['DZ']

Country                               Algeria
Pop_Density                              18.0
Land_Area                           2381741.0
Birth_Rate                              24.28
CO2_Emissions                        150006.0
CPI                                    151.36
Fertility_Rate                           3.02
GDP                            169988000000.0
Infant mortality_per_1k                  20.1
Life_Expectancy                          76.7
Maternal_Mortality_per_100k             112.0
Minimum_Wage                             0.95
Official Language                      Arabic
oop_health_exp                           0.28
Physicians_per_1k                        1.72
Population                         43053054.0
Unemployment_Rate                        0.12
Name: DZ, dtype: object

##Update Notebook

In [9]:
# Delete Vatican City from DataFrame
world_health_df = world_health_df.drop('VA')

In [10]:
# check work
world_health_df.tail(10)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
UZ,Uzbekistan,79.0,447400.0,23.30,91811.0,NaN,2.42,5.792129e+10,19.1,71.6,29.0,0.24,Uzbek,0.43,2.37,33580650.0,0.06
VC,Saint Vincent and the Grenadines,284.0,389.0,14.24,220.0,109.67,1.89,8.253852e+08,14.8,72.4,68.0,1.16,English,0.21,0.66,100455.0,0.19
VE,Venezuela,32.0,912050.0,17.88,164175.0,2740.27,2.27,4.823590e+11,21.4,72.1,125.0,0.01,Spanish,0.46,1.92,28515829.0,0.09
VN,Vietnam,314.0,331210.0,16.75,192668.0,163.52,2.05,2.619210e+11,16.5,75.3,43.0,0.73,Vietnamese,0.44,0.82,96462106.0,0.02
VU,Vanuatu,25.0,12189.0,29.60,147.0,117.13,3.78,9.170589e+08,22.3,70.3,72.0,1.56,French,0.09,0.17,299882.0,0.04
WS,Samoa,70.0,2831.0,24.38,246.0,117.56,3.88,8.506550e+08,13.6,73.2,43.0,0.78,Samoan,0.12,0.34,202506.0,0.08
YE,Yemen,56.0,527968.0,30.45,10609.0,157.58,3.79,2.691440e+10,42.9,66.1,164.0,NaN,Arabic,0.81,0.31,29161922.0,0.13
ZA,South Africa,49.0,1219090.0,20.51,476644.0,158.93,2.41,3.514320e+11,28.5,63.9,119.0,NaN,Afrikaans,0.08,0.91,58558270.0,0.28
ZM,Zambia,25.0,752618.0,36.19,5141.0,212.31,4.63,2.306472e+10,40.4,63.5,213.0,0.24,English,0.28,1.19,17861030.0,0.11
ZW,Zimbabwe,38.0,390757.0,30.68,10983.0,105.51,3.62,2.144076e+10,33.9,61.2,458.0,NaN,Shona,0.26,0.21,14645468.0,0.05

###Question 4: What is the official language of the nation on the 186th row?

In [11]:
# offocial language of nation on 186th row

world_health_df.iloc[185]

Country                             Venezuela
Pop_Density                              32.0
Land_Area                            912050.0
Birth_Rate                              17.88
CO2_Emissions                        164175.0
CPI                                   2740.27
Fertility_Rate                           2.27
GDP                            482359000000.0
Infant mortality_per_1k                  21.4
Life_Expectancy                          72.1
Maternal_Mortality_per_100k             125.0
Minimum_Wage                             0.01
Official Language                     Spanish
oop_health_exp                           0.46
Physicians_per_1k                        1.92
Population                         28515829.0
Unemployment_Rate                        0.09
Name: VE, dtype: object

##Sort dataframe by infant mortaility. highest to lowest

In [12]:
#sort by infant mortality, high to low
world_health_df = world_health_df.sort_values('Infant mortality_per_1k', ascending = False)

In [13]:
# Top 10 nations with the highest infant mortality. What continent?
world_health_df.head(10)

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate
Abbreviation,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02
CD,Democratic Republic of the Congo,40.0,2344858.0,41.18,2021.0,133.85,5.92,4.731962e+10,68.2,60.4,473.0,0.18,French,0.37,0.07,86790567.0,0.04
LS,Lesotho,71.0,30355.0,26.81,2512.0,155.86,3.14,2.460072e+09,65.7,53.7,544.0,0.41,English,0.17,0.07,2125268.0,0.23
GN,Guinea,53.0,245857.0,36.36,2996.0,262.95,4.70,1.359028e+10,64.9,61.2,576.0,NaN,French,0.55,0.08,12771246.0,0.04
SS,South Sudan,18.0,644329.0,35.01,1727.0,4583.71,4.70,1.199780e+10,63.7,57.6,1150.0,NaN,English,0.61,NaN,11062113.0,0.12
GQ,Equatorial Guinea,50.0,28051.0,33.24,5655.0,124.35,4.51,1.102677e+10,62.6,58.4,301.0,1.05,Spanish,0.72,0.40,1355986.0,0.06

##Create new dataframe for countries whose official language is Spanish

In [14]:
# How many rows are in the new dataframe?

# create filter
spanish_language_filter = world_health_df['Official Language'] == 'Spanish'

# apply filter
world_health_df[spanish_language_filter]

#count
world_health_df[spanish_language_filter].shape

(19, 17)

In [15]:
# mean infant mortality per 1k infants in countires whose official language is Spanish

world_health_df[spanish_language_filter]['Infant mortality_per_1k'].mean()

np.float64(15.557894736842103)

In [16]:
# what is the median maternal mortality in counties whose official langiage is Spanish

world_health_df[spanish_language_filter]['Maternal_Mortality_per_100k'].median()

65.0

In [17]:
# create GDP per capita field

world_health_df['GDP_per_capita'] = world_health_df['GDP'] / world_health_df['Population']

In [18]:
# check work
world_health_df.head()

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_per_capita
Abbreviation,,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04,467.907441
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04,504.462543
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11,305.689071
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08,2229.856562
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02,709.540310

In [19]:
# Sort by GDP per capita, high to low
world_health_df = world_health_df.sort_values('GDP_per_capita', ascending = False)

In [20]:
# check work
world_health_df.iloc[3]

Country                           Switzerland
Pop_Density                             219.0
Land_Area                             41277.0
Birth_Rate                               10.0
CO2_Emissions                         34477.0
CPI                                     99.55
Fertility_Rate                           1.52
GDP                            703082000000.0
Infant mortality_per_1k                   3.7
Life_Expectancy                          83.6
Maternal_Mortality_per_100k               5.0
Minimum_Wage                              NaN
Official Language                      German
oop_health_exp                           0.28
Physicians_per_1k                         4.3
Population                          8574832.0
Unemployment_Rate                        0.05
GDP_per_capita                   81993.676378
Name: CH, dtype: object

In [21]:
# Average maternal mortality rate per 100k for all nations?

world_health_df['Maternal_Mortality_per_100k'].mean()

np.float64(160.39226519337018)

In [22]:
# WHat percentage of health care is paid out of pocket by country with the lowest infant mortality?
world_health_df.sort_values('Infant mortality_per_1k', ascending = True).head()

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_per_capita
Abbreviation,,,,,,,,,,,,,,,,,,
FI,Finland,18.0,338145.0,8.6,45871.0,112.33,1.41,2.687610e+11,1.4,81.7,3.0,NaN,Swedish,0.20,3.81,5520314.0,0.07,48685.817510
IS,Iceland,3.0,103000.0,12.0,2065.0,129.00,1.71,2.418804e+10,1.5,82.7,4.0,NaN,Icelandic,0.17,4.08,361313.0,0.03,66944.825509
SM,San Marino,566.0,61.0,6.8,NaN,110.63,1.26,1.637931e+09,1.7,85.4,NaN,NaN,Italian,0.18,6.11,33860.0,NaN,48373.627702
SI,Slovenia,103.0,20273.0,9.4,12633.0,111.05,1.60,5.374216e+10,1.7,81.0,7.0,5.25,Slovene language,0.13,3.09,2087946.0,0.04,25739.247814
JP,Japan,347.0,377944.0,7.4,1135886.0,105.48,1.42,5.081770e+12,1.8,84.2,5.0,6.77,NaN,0.13,2.41,126226568.0,0.02,40259.115656

In [23]:
# WHat percentage of health care is paid out of pocket by country with the highest infant mortality?
world_health_df.sort_values('Infant mortality_per_1k', ascending = False).head()

,Country,Pop_Density,Land_Area,Birth_Rate,CO2_Emissions,CPI,Fertility_Rate,GDP,Infant mortality_per_1k,Life_Expectancy,Maternal_Mortality_per_100k,Minimum_Wage,Official Language,oop_health_exp,Physicians_per_1k,Population,Unemployment_Rate,GDP_per_capita
Abbreviation,,,,,,,,,,,,,,,,,,
CF,Central African Republic,8.0,622984.0,35.35,297.0,186.86,4.72,2.220307e+09,84.5,52.8,829.0,0.37,French,0.40,0.06,4745185.0,0.04,467.907441
SL,Sierra Leone,111.0,71740.0,33.41,1093.0,234.16,4.26,3.941474e+09,78.5,54.3,1120.0,0.57,English,0.38,0.03,7813215.0,0.04,504.462543
SO,Somalia,25.0,637657.0,41.75,645.0,NaN,6.07,4.720727e+09,76.6,57.1,829.0,NaN,Arabic,NaN,0.02,15442905.0,0.11,305.689071
NG,Nigeria,226.0,923768.0,37.91,120369.0,267.51,5.39,4.481200e+11,75.7,54.3,917.0,0.54,English,0.72,0.38,200963599.0,0.08,2229.856562
TD,Chad,13.0,1284000.0,42.17,1016.0,117.70,5.75,1.131495e+10,71.4,54.0,1140.0,0.60,French,0.56,0.04,15946876.0,0.02,709.540310